version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - mv target/java-hello-world.war java-hello-world.war
artifacts:
  files:
     - java-hello-world.war
     - .ebextensions/**/*
